import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/layout/footer";
import Header from "./components/layout/header";
import { Inter } from 'next/font/google'


const inter = Inter({
  subsets: ['latin', 'cyrillic'], 
  variable: '--font-inter',      
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className = {inter.variable} lang="en">
      <body className={` w-[1440] mx-auto font-inter`}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
